# Generated by Django 5.2.5 on 2025-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0003_appointment_created_at_appointment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
